### Add a new todo
POST http://localhost:5194/api/tasks
Content-Type: application/json

{
  "title": "Do second Assignment",
  "priority": "high",
  "assignee": "Emmaneul Balogun",
  "status": "completed",
  "description": "todo blah blah blah",
  "dueDate": "2025-03-09"
}

### Get all todos
GET http://localhost:5194/api/tasks

### Get a todo
GET http://localhost:5194/api/tasks/2

### Update a todo
PATCH  http://localhost:5194/api/tasks/2
Content-Type: application/json

{
  "title": "Do Assignment",
}

### Delete a todo
DELETE http://localhost:5194/api/tasks/2
